name : my First Workflow

on : push

jobs : 
    first_job: 
        runs-on: ubuntu-latest
        steps:
            - name : Checkout Repo
              uses: actions/checkout@v4

            - name : List & Read File
              run: |
                 echo "my first Github Action Job"
                 ls -ltra
                 car README.md

            - name : Generate ASCII Artwork
              run : cowsay -f dragon "Run for cover" >> dragon.txt
            #- name: list files
            # run: ls

            #- name: ReadFile
            #  run: cat README.md